---
name: Build-Docs

# Build during PRs and Pushes to the repo at any branch
on:
  - pull_request
  - push

jobs:
  build-docs:
    name: Construct sphinx version docs
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python - implement a matrix afterwards
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Install package docs
      - name: Install docs dependencies
        run: |
          pip install -q -e .[docs]

      # Build current version of documentation and emit as artifact
      - name: Build documentation of current commit
        run: make -C docs/ html

      # Build all versions of documentation
      - name: Build version stack of documentation
        run: |
          git fetch --all
          sphinx-multiversion docs/source docs/build/html

      # Store documentation artifact for deployment
      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
          name: multidocs
          path: docs/build


  deploy-docs:
    name: Publish docs to gh-pages
    runs-on: ubuntu-latest
    needs: build-docs
    steps:

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Download documentation
      - name: Download multi-docs
        uses: actions/download-artifact@v2
        with:
          name: multidocs
          path: docs/build/

      # Set up re-direct index.html page
      - name: Set up index redirect
        shell: bash
        run: |
          ls
          git fetch --prune --unshallow --tags
          LATEST_TAG=$(git describe --abbrev=0 --tags)
          echo "<meta http-equiv='refresh' content='0; url=./${LATEST_TAG}/index.html' />" > ./docs/build/html/index.html

      # Publish
      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true
