---
name: Build-Test

on:
  release:
    types: [published]
  pull_request:
  push:


jobs:
  build:
    name: Install Niviz dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: acions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -q -e .[buildtest]
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --statistics
      - name: Run pytest
        run: |
          cd niviz
          pytest tests/
